### ISSUE TITLE
リンク先が 404 です

### ISSUE THREAD

**Issue by skmkzyk** [jpwinsup/blog#4]
「以下のページに移動しました」のリンク先が 404 です。

以下の URL が正しいかと思っています。。
https://jpwinsup.github.io/blog/2022/03/02/RemoteDesktopService/AVD/AVD-ARM-Japanese-image/﻿

---

#### Document Details

* Article ID: 7862a041-b601-5745-96d7-1af70e667bb4
* TITLE: WVD ARM 日本語化イメージ作成手順について
* URL https://jpwinsup.github.io/blog/2021/01/20/RemoteDesktopService/WVD/WVD-ARM-Japanese-image/
* SourceFileName: source/_posts/RemoteDesktopService/WVD/WVD-ARM-Japanese-image.md

**Comment by Erin-Li-MS** [comment]
404 のエラーを修正いたしました。
https://jpwinsup.github.io/blog/2021/01/20/RemoteDesktopService/AVD/AVD-ARM-Japanese-image/
へのアクセスはできるようになりました。

**Comment by yastakahashi** [comment]
Updated the link and close this issue
